[demonstration]
messageFromChezmoiData = "Hello_from_.chezmoidata.toml.tmpl!"

## -- Make sure you use the right answer or install script will fail ###
# Make sure proper AUR Helper is use NO Upperscript. Either paru or yay only is accepted
# The rest Change to Y for Yes and N for No.
[variables]
# ========================
# Changeable Parameters
# ========================
# This section contains parameters that you can modify to suit your specific dotfile setup.
# Adjust the values as needed.

# - Type of AUR helper
#   Options: "yay" or "paru"
aur_helper = "yay"

# - Do you have any NVIDIA GPU in your system?
#   Options: "true" or "false"
nvidia = true

# -Install XDG-DESKTOP-PORTAL-HYPRLAND? (For proper Screen Share ie OBS)
#   Options: "true" or "false"
xdph = true

# - Would you like to change time to local time (not UTC)?
#   Options: "true" or "false"
time = true

# -Do you want to configure Bluetooth?
#   Options: "true" or "false"
bluetooth = true

# These are the sub-questions of the above choices

# - This script will add your user to the 'input' group.
#   Please note that adding yourself to the 'input' group might be necessary for waybar keyboard-state functionality.
#   Options: "true" or "false"
input_group_choid = true

# - XDG-desktop-portal-KDE & GNOME (if installed) should be manually disabled or removed!
#   Script can't remove nor disable it.
#   Would you like to try to remove other XDG-Desktop-Portal-Implementations?
#   Options: "true" or "false"
XDPH1 = true

# - Install zsh
#   Options: "true" or "false"
zsh = true

# - Install oh-my-zsh (note that starship and oh-my-zsh cannot be installed together)
#   Options: "true" or "false"
oh_my_zsh = false

# - Install starship for zsh (note that starship and oh-my-zsh cannot be installed together)
#   Options: "true" or "false"
starship = true

# - Would you like to blacklist nouveau?
#   Options: "true" or "false"
# blacklist_nouveau = true


# ========================

# ========================
# Unchangeable Parameters
# ========================
# This section contains parameters that you should not modify unless you know what you are doing.
# There is a risk to break the dotfile setup if you change these values.

# -Install GTK themes (required for Dark/Light function)?
#   Options: "true" or "false"
gtk_themes = true


# - Do you want to install Thunar file manager?
#   Options: "true" or "false"
thunar = true

# -Install & configure SDDM log-in Manager plus (OPTIONAL) SDDM Theme?
#   Options: "true" or "false"
sddm = true

# These are the sub-questions of the above choices

# - SDDM is already installed. Would you like to manually install sddm-git to remove it?
#   This requires manual intervention.
#   Options: "Y" or "N"
manual_install_sddm = "N"

# - OPTIONAL - Would you like to install SDDM themes?
#   Options: "Y" or "N"
install_sddm_theme = "N"

# ========================
