---
- name: Install Hyprland plugins
  ansible.builtin.command: "hyprpm add {{ item.key }}"
  loop: "{{ hyprland_plugins | dict2items }}"
  register: plugin_install
  changed_when: "'already installed' not in plugin_install.stderr"
  failed_when:
    - plugin_install.rc != 0
    - "'already installed' not in plugin_install.stderr"

- name: Enable Hyprland plugins
  ansible.builtin.command: "hyprpm enable {{ item.value }}"
  loop: "{{ hyprland_plugins | dict2items }}"
  register: plugin_enable
  changed_when: "'already enabled' not in plugin_enable.stderr"
  failed_when:
    - plugin_enable.rc != 0
    - "'already enabled' not in plugin_enable.stderr"
