---
- name: Import AUR builder setup
  ansible.builtin.import_tasks: aur_setup.yml
  tags: ["packages", "aur_setup"]

- name: Import packages download task
  ansible.builtin.import_tasks: packages.yml
  tags: ["packages", "install_package"]

# Install Hyprland plugins if configured
- name: Import Hyprland plugins download task
  ansible.builtin.include_tasks: hyprland_plugins.yml
  when: hyprland_plugins is defined and hyprland_plugins | length > 0
