---
- name: Import packages download task
  ansible.builtin.import_tasks: packages.yml
  tags: ["packages", "install_package"]

- name: Import services activation task
  ansible.builtin.import_tasks: services.yml
  tags: ["packages", "services"]

# - name: Install Yazi plugins
#   ansible.builtin.import_tasks: yazi_plugins.yml
#   tags: ["packages", "yazi", "plugins"]

# Install Hyprland plugins if configured
# - name: Import Hyprland plugins download task
#   ansible.builtin.include_tasks: hyprland_plugins.yml
#   when: hyprland_plugins is defined and hyprland_plugins | length > 0
